# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'strava-weekly'
primary_region = 'den'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 20
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
